language: python

dist: xenial

python: "3.7"

cache:
  pip: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libasound2-dev

install:
  - pip install pylint

script:
  - pylint spfy