#!/bin/bash

BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
PURPLE='\033[0;34m'
CYAN='\033[0;35m'
GRAY='\033[0;36m'

BOLD_BLACK='\033[1;30m'
BOLD_RED='\033[1;31m'
BOLD_GREEN='\033[1;32m'
BOLD_ORANGE='\033[1;33m'
BOLD_PURPLE='\033[1;34m'
BOLD_CYAN='\033[1;35m'
BOLD_GRAY='\033[1;36m'

NC='\033[0m'

TEXTS[0]="Mistakes, we all make them. Especially you."
TEXTS[1]="Have no fear of perfection - you'll never reach it."
TEXTS[2]="They say we learn from failure ¯\_(ツ)_/¯ . Well, this is definitely a failure."
TEXTS[3]="Seems like you are so smart, that even you fail to understand what you write sometimes."
TEXTS[4]="You can do better than that! Probably."
TEXTS[5]="(╯°□°）╯︵ ┻━┻"
TEXTS[6]="ಠ_ಠ"
TEXTS[7]="ლ(╹◡╹ლ)"
TEXTS[8]="Look who's too confident today!"
TEXTS[9]="Shit happens.. A bit too often lately"
TEXTS[10]="I'm not saying I hate you. But I would probably unplug your life support to charge my phone"
TEXTS[11]="Keep rolling your eyes. Maybe you'll find a brain back there."
TEXTS[12]="Oh I'm sorry I didn't get that. I don't speak idiot"
TEXTS[13]="I see you never make the same mistake twice. You make it five or six times, just to be sure"

TEXT=${TEXTS[$(($RANDOM % ${#TEXTS[@]}))]}

FOLDER=spfy
CHANGED=0
STATUS=0

if ! isort -j4 -rc -c -tc $FOLDER 1>/dev/null 2>/dev/null; then
    CHANGED=1
    printf "${BOLD_GREEN}Sorting imports 🙄${NC}\n"
    isort -j4 -y -rc -tc $FOLDER
    echo ''
fi

if ! black --check --fast $FOLDER 1>/dev/null 2>/dev/null; then
    test $(uname) = 'MINGW64_NT-6.1' || CHANGED=1
    printf "${BOLD_PURPLE}Removing ugly code 🤢${NC}\n"
    black $FOLDER
    echo ''
fi

if [[ $CHANGED -ne 0 ]]; then
    printf "${BOLD_ORANGE}I changed some files ¯\_(ツ)_/¯\nYou'll have to add them again before committing${NC}\n"
    exit $CHANGED
fi

printf "${BOLD_RED}Checking for shitty code 💩${NC}\n"
if ! pylint $FOLDER; then
    echo ''
    printf "${BOLD_ORANGE}${TEXT}${NC}\n"
    exit 1
fi
